---
extends: default

rules:
  line-length:
    max: 120  # Adjust line limit
  truthy:
    permit-implicit: true  # Allow implicit truthy values
  document-start: disable  # Disable document start rule
