# backend-mqtt-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: darkseek-backend-mqtt
spec:
  selector:
    app: darkseek-backend-mqtt
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP  # Change to ClusterIP if only internal pods need to hit the health check
