# ClusterRoleBinding for project-wide access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: darkseek-maga-binding
subjects:
- kind: User
  name: darkseek-maga@ascendant-lore-452208-b6.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Adjust role as needed (e.g., view, edit)
  apiGroup: rbac.authorization.k8s.io
