# k8s/db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkseek-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkseek-db
  template:
    metadata:
      labels:
        app: darkseek-db
    spec:
      initContainers:
      - name: init-postgres-data
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            mkdir -p /var/lib/postgresql/data/pgdata
            chown -R 999:999 /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
