# k8s/db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkseek-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkseek-db
  template:
    metadata:
      labels:
        app: darkseek-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: darkseek-secrets
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "100m"    # Minimum CPU needed
            memory: "256Mi" # Minimum memory needed
          limits:
            cpu: "500m"    # Maximum CPU allowed
            memory: "512Mi" # Maximum memory allowed      
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: darkseek-postgres-pvc
     
          
