# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: darkseekdb
spec:
  selector:
    app: darkseekdb
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP  # Internal only
