# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkseek-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkseek-redis
  template:
    metadata:
      labels:
        app: darkseek-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
  resources:
      requests:
        cpu: "100m"    # Minimum CPU needed
        memory: "256Mi" # Minimum memory needed
      limits:
        cpu: "500m"    # Maximum CPU allowed
        memory: "512Mi" # Maximum memory allowed        
        
