# k8s/06-allow-debug-to-backend.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-debug-nuclear
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debug-mqtt # ONLY for your debugger pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {} # Open Inbound
  egress:
  - {} # Open Outbound
