---
# .github/workflows/purge-gcr.yaml
name: PURGE GCR — ONE TIME ONLY

on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT (REQUIRED)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}        # ← YOUR PAT HERE
          persist-credentials: true              # ← REQUIRED FOR git push

      - name: Execute purge
        run: |
          chmod +x k8s/purge-gcr.sh
          cd k8s && ./purge-gcr.sh

      - name: Commit & push
        run: |
          git config user.name "Frank Aigrillo"
          git config user.email "frank@darkseek.com"
          git add .
          git commit -m "GCR PURGED FOREVER — Artifact Registry reigns" || echo "No changes"
          git push
